### ISSUE TITLE
OSError: [Errno 28] No space left on device: './checkpoints/ckpt-0/tensor00000_000' -> '/dev/shm/tmpeq5bn6yp'

### ISSUE THREAD

**Issue by bluevisor** [xai-org/grok-1#138]
I'm using Ubuntu 22.04.3 in WSL2

is /dev/shm/ a ramdisk? does it mean my 64G of ram is not enough? can I set it to use my ssd instead?

complete log:
`bluevisor@AMD3090:/mnt/c/grok-1$ python3 run.py
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:rank:Initializing mesh for self.local_mesh_config=(1, 1) self.between_hosts_config=(1, 1)...
INFO:rank:Detected 1 devices in mesh
INFO:rank:partition rules: <bound method LanguageModelConfig.partition_rules of LanguageModelConfig(model=TransformerConfig(emb_size=6144, key_size=128, num_q_heads=48, num_kv_heads=8, num_layers=64, vocab_size=131072, widening_factor=8, attn_output_multiplier=0.08838834764831845, name=None, num_experts=8, capacity_factor=1.0, num_selected_experts=2, init_scale=1.0, shard_activations=True, data_axis='data', model_axis='model'), vocab_size=131072, pad_token=0, eos_token=2, sequence_len=8192, model_size=6144, embedding_init_scale=1.0, embedding_multiplier_scale=78.38367176906169, output_multiplier_scale=0.5773502691896257, name=None, fprop_dtype=<class 'jax.numpy.bfloat16'>, model_type=None, init_scale_override=None, shard_embeddings=True)>
INFO:rank:(1, 256, 6144)
INFO:rank:(1, 256, 131072)
INFO:rank:State sharding type: <class 'model.TrainingState'>
INFO:rank:(1, 256, 6144)
INFO:rank:(1, 256, 131072)
INFO:rank:Loading checkpoint at ./checkpoints/ckpt-0
Traceback (most recent call last):
  File "/mnt/c/grok-1/run.py", line 73, in <module>
    main()
  File "/mnt/c/grok-1/run.py", line 64, in main
    inference_runner.initialize()
  File "/mnt/c/grok-1/runners.py", line 294, in initialize
    params = runner.load_or_init(dummy_data)
  File "/mnt/c/grok-1/runners.py", line 238, in load_or_init
    state = xai_checkpoint.restore(
  File "/mnt/c/grok-1/checkpoint.py", line 196, in restore
    loaded_tensors = load_tensors(ckpt_shapes_flat, ckpt_path, between_hosts_config)
  File "/mnt/c/grok-1/checkpoint.py", line 107, in load_tensors
    return [f.result() for f in fs]
  File "/mnt/c/grok-1/checkpoint.py", line 107, in <listcomp>
    return [f.result() for f in fs]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/c/grok-1/checkpoint.py", line 72, in fast_unpickle
    with copy_to_shm(path) as tmp_path:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/mnt/c/grok-1/checkpoint.py", line 52, in copy_to_shm
    shutil.copyfile(file, tmp_path)
  File "/usr/lib/python3.10/shutil.py", line 267, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.10/shutil.py", line 156, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.10/shutil.py", line 142, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: './checkpoints/ckpt-0/tensor00000_000' -> '/dev/shm/tmpuz1zhrdt'`

**Comment by Tansien** [comment]
You won't be able to run this on a computer with 64GB of RAM and a 3090.

**Comment by Mydtlwn** [comment]
this file is 300G。

**Comment by cheungxiongwei** [comment]
you need 48*8 RAM

**Comment by bluevisor** [comment]
My ram usage peaked around 40G when crashed, while vram is at consistent 20G, it feels like there's room for improvement...

**Comment by bluevisor** [comment]
ok, by setting the /dev/shm to a bigger size, I got a little further:

`sudo mount -o remount,size=48G /dev/shm`
