### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MARKELOX** [xai-org/grok-1#18]
C:\Users\MARKELOX\Desktop\grok-main>py run.py
INFO:jax._src.xla_bridge:Unable to initialize backend 'cuda':
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': UNIMPLEMENTED: LoadPjrtPlugin is not implemented on windows yet.
INFO:rank:Initializing mesh for self.local_mesh_config=(1, 8) self.between_hosts_config=(1, 1)...
INFO:rank:Detected 1 devices in mesh
Traceback (most recent call last):
  File "C:\Users\MARKELOX\Desktop\grok-main\run.py", line 72, in <module>
    main()
  File "C:\Users\MARKELOX\Desktop\grok-main\run.py", line 63, in main
    inference_runner.initialize()
  File "C:\Users\MARKELOX\Desktop\grok-main\runners.py", line 282, in initialize
    runner.initialize(
  File "C:\Users\MARKELOX\Desktop\grok-main\runners.py", line 181, in initialize
    self.mesh = make_mesh(self.local_mesh_config, self.between_hosts_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MARKELOX\Desktop\grok-main\runners.py", line 586, in make_mesh
    device_mesh = mesh_utils.create_hybrid_device_mesh(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MARKELOX\AppData\Local\Programs\Python\Python312\Lib\site-packages\jax\experimental\mesh_utils.py", line 373, in create_hybrid_device_mesh
    per_granule_meshes = [create_device_mesh(mesh_shape, granule)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MARKELOX\AppData\Local\Programs\Python\Python312\Lib\site-packages\jax\experimental\mesh_utils.py", line 302, in create_device_mesh
    raise ValueError(f'Number of devices {len(devices)} must equal the product '
ValueError: Number of devices 1 must equal the product of mesh_shape (1, 8)

**Comment by AlpinDale** [comment]
You seem to need exactly 8 GPUs to run this. Or multiples of 8.

**Comment by MARKELOX** [comment]
It's a pity, I'm waiting for a possible solution or to pay $20 per month again :(

**Comment by Godofnothing** [comment]
This stuff requires at least 4 GPU with 80Gb to simply fit into the memory in 8bit, 8GPU to fit in bf16.

**Comment by EvertondeBem** [comment]
> This beast requires 8 GPU with 80Gb to simply fit into the memory in bf16.

No. 8 GPU runs at 4bits. and need to be 8bits.
Needs be 80Gb VRAM in only one GPU w/ 80GB VRAM (like a Nvidia A100)

**Comment by blackHorsePrince** [comment]
what you use compiler？？

**Comment by xSetech** [comment]
See also, #38
