### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\dev\\shm\\tmpolgxfn9p'

### ISSUE THREAD

**Issue by menyunlei** [xai-org/grok-1#260]
![Snipaste_2024-03-22_00-02-27](https://github.com/xai-org/grok-1/assets/53305696/449c73ee-74eb-4cbc-b4df-4fe3315bfe9b)
should I create the file at that path?

**Comment by yarodevuci** [comment]
@menyunlei check other threads, there been answers already to this

**Comment by superguo** [comment]
要懂 Linux、k8s/docker、CUDA或TPU 之类的才行。要本地跑的话，至少要8块A100 GPU卡（约80万人民币），一般是服务器才能装得了这种配置。

**Comment by yangjiandan** [comment]
update checkpoint.py:50 may fix this error
-    tmp_dir = "/dev/shm/"
+    tmp_dir = "/tmp/shm/"

**Comment by vjeka1** [comment]
I have the same problem
INFO:rank:Loading checkpoint at ./checkpoints/ckpt-0
Traceback (most recent call last):
  File "F:\Grok\grok-1\run.py", line 72, in <module>
    main()
  File "F:\Grok\grok-1\run.py", line 63, in main
    inference_runner.initialize()
  File "F:\Grok\grok-1\runners.py", line 294, in initialize
    params = runner.load_or_init(dummy_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Grok\grok-1\runners.py", line 238, in load_or_init
    state = xai_checkpoint.restore(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Grok\grok-1\checkpoint.py", line 196, in restore
    loaded_tensors = load_tensors(ckpt_shapes_flat, ckpt_path, between_hosts_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Grok\grok-1\checkpoint.py", line 107, in load_tensors
    return [f.result() for f in fs]
            ^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Grok\grok-1\checkpoint.py", line 72, in fast_unpickle
    with copy_to_shm(path) as tmp_path:
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "F:\Grok\grok-1\checkpoint.py", line 50, in copy_to_shm
    fd, tmp_path = tempfile.mkstemp(dir=tmp_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\tempfile.py", line 357, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\tmp\\shm\\tmp1rv26fpm'

All files in F:\Grok\grok-1


F:\Grok\grok-1

26.03.2024  21:35    <DIR>          .
26.03.2024  21:35    <DIR>          ..
26.03.2024  21:47             7 392 checkpoint.py
26.03.2024  21:39    <DIR>          checkpoints
18.03.2024  11:08            11 358 LICENSE
18.03.2024  11:13            40 040 md5sum.txt
26.03.2024  21:28            45 779 model.py
26.03.2024  21:28               170 pyproject.toml
26.03.2024  21:28             2 145 README.md
18.03.2024  11:08             1 762 RELEASE
26.03.2024  21:24               146 requirements.txt
26.03.2024  21:32             2 264 run.py
26.03.2024  21:28            21 845 runners.py
26.03.2024  21:28         2 229 219 tokenizer.model
26.03.2024  21:45    <DIR>          __pycache__
