### ISSUE TITLE
Nr. of devices needed

### ISSUE THREAD

**Issue by zcobol** [xai-org/grok-1#38]
Running `python run.py` on a single Nvidia GPU it fails with `ValueError: Number of devices 1 must equal the product of mesh_shape (1, 8)`

Can the nr of devices be adjusted to 1 only?

**Comment by nickorlabs** [comment]
INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:rank:Initializing mesh for self.local_mesh_config=(1, 8) self.between_hosts_config=(1, 1)...
INFO:rank:Detected 2 devices in mesh
Traceback (most recent call last):
  File "/opt/grok-1/run.py", line 72, in <module>
    main()
  File "/opt/grok-1/run.py", line 63, in main
    inference_runner.initialize()
  File "/opt/grok-1/runners.py", line 282, in initialize
    runner.initialize(
  File "/opt/grok-1/runners.py", line 181, in initialize
    self.mesh = make_mesh(self.local_mesh_config, self.between_hosts_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/runners.py", line 586, in make_mesh
    device_mesh = mesh_utils.create_hybrid_device_mesh(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in create_hybrid_device_mesh
    per_granule_meshes = [create_device_mesh(mesh_shape, granule)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in <listcomp>
    per_granule_meshes = [create_device_mesh(mesh_shape, granule)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 302, in create_device_mesh
    raise ValueError(f'Number of devices {len(devices)} must equal the product '
ValueError: Number of devices 2 must equal the product of mesh_shape (1, 8)

this what you get?

**Comment by yarodevuci** [comment]
i did put 1 instead of 8

**Comment by yarodevuci** [comment]
I keep getting same error : PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\dev\\shm\\tmpp53ohpcl'

**Comment by AcebqAce** [comment]
> INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory INFO:rank:Initializing mesh for self.local_mesh_config=(1, 8) self.between_hosts_config=(1, 1)... INFO:rank:Detected 2 devices in mesh Traceback (most recent call last): File "/opt/grok-1/run.py", line 72, in main() File "/opt/grok-1/run.py", line 63, in main inference_runner.initialize() File "/opt/grok-1/runners.py", line 282, in initialize runner.initialize( File "/opt/grok-1/runners.py", line 181, in initialize self.mesh = make_mesh(self.local_mesh_config, self.between_hosts_config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/grok-1/runners.py", line 586, in make_mesh device_mesh = mesh_utils.create_hybrid_device_mesh( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in create_hybrid_device_mesh per_granule_meshes = [create_device_mesh(mesh_shape, granule) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 373, in per_granule_meshes = [create_device_mesh(mesh_shape, granule) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/groq-1/lib/python3.11/site-packages/jax/experimental/mesh_utils.py", line 302, in create_device_mesh raise ValueError(f'Number of devices {len(devices)} must equal the product ' ValueError: Number of devices 2 must equal the product of mesh_shape (1, 8)
> 
> this what you get?

I have the same issues, is there a way to resolve this?

**Comment by zRzRzRzRzRzRzR** [comment]
same issue even all requirements install.

**Comment by nickorlabs** [comment]
I have 2 GPUs and everything installed ok as well.

**Comment by bluevisor** [comment]
in run.py, I changed line 60: 
`local_mesh_config=(1, 8),`
to
`local_mesh_config=(1, 1),`

(I have 1 3090)

**Comment by nickorlabs** [comment]
Ok got a little further this time!

Traceback (most recent call last):
  File "/opt/grok-1/run.py", line 72, in <module>
    main()
  File "/opt/grok-1/run.py", line 63, in main
    inference_runner.initialize()
  File "/opt/grok-1/runners.py", line 294, in initialize
    params = runner.load_or_init(dummy_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/runners.py", line 238, in load_or_init
    state = xai_checkpoint.restore(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/checkpoint.py", line 196, in restore
    loaded_tensors = load_tensors(ckpt_shapes_flat, ckpt_path, between_hosts_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/checkpoint.py", line 107, in load_tensors
    return [f.result() for f in fs]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/checkpoint.py", line 107, in <listcomp>
    return [f.result() for f in fs]
            ^^^^^^^^^^
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/grok-1/checkpoint.py", line 72, in fast_unpickle
    with copy_to_shm(path) as tmp_path:
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/grok-1/checkpoint.py", line 52, in copy_to_shm
    shutil.copyfile(file, tmp_path)
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/shutil.py", line 269, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/shutil.py", line 158, in _fastcopy_sendfile
    raise err from None
  File "/opt/anaconda3/envs/groq-1/lib/python3.11/shutil.py", line 144, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: './checkpoints/ckpt-0/tensor00000_000' -> '/dev/shm/tmpi8_qagu5'

I have 2 Quadro 5000s do I not have enough vRAM?

**Comment by bluevisor** [comment]
I'm at the same point, GPT told me /dev/shm is a ramdisk, which means we don't have enough ram, not vram.

I have 64G, not sure how much we need... would 128 be enough?

**Comment by nickorlabs** [comment]
I have 128 GB on this rig, with the two cards its like 32 GB, this is why I assumed vRAM.  Maybe I could be wrong.

**Comment by bluevisor** [comment]
bummer... guess we'll just have to wait for gguf...

**Comment by nickorlabs** [comment]
Possibly.  I might spin up a runpod, or wait for GGUF, I was reading people needing 8 GPUs.

**Comment by nickorlabs** [comment]
get it up and running?

**Comment by yarodevuci** [comment]
> looks like i have to set
> 
> ```
>         widening_factor=6,
>         num_kv_heads=6,
> ```
> 
> in the TransformerConfig to the number of devices as well

did it work after?

**Comment by nickorlabs** [comment]
Im seeding (again), took me most the evening last night to download, and I have 2000mbit download

**Comment by ad1tyac0des** [comment]
> I'm at the same point, GPT told me /dev/shm is a ramdisk, which means we don't have enough ram, not vram.
> 
> I have 64G, not sure how much we need... would 128 be enough?


My system has 192GB of RAM, I also encountered same.
 OSError: [Errno 28] No space left on device: './checkpoints/ckpt-0/tensor00000_000' -> '/dev/shm/tmpbeofn6hn

**Comment by yarodevuci** [comment]
@ad1tyac0des it creates temp folder with over 300GB in it, do you have that space on the hard drive?

**Comment by toughcoding** [comment]
Is anybody here who saw live presentation where X developers run it using exact commands or we all trying to test it for them?

**Comment by pwxpwxtop** [comment]
坑爹，为了下载它，花费了我一天的心血

**Comment by KHARAPSY** [comment]
I succeeded increasing space and get rid of this error 
"OSError: [Errno 28] No space left on device: './checkpoints/ckpt-0/tensor00000_000' -> '/dev/shm/tmpi8_qagu5'" 

but in exchange to do that I end up with system crashed instead, so I will give up for now. I don't have enough RAM to run Grok-1 neither enough money to upgrade my hardware"

**Comment by zRzRzRzRzRzRzR** [comment]
> same issue even all requirements install. I am using 8 GPUs

I change it to 8 x A100 GPU and it cost 65G memory in per GPU to run this model, The resources required to run this model are a bit large

<img width="721" alt="image" src="https://github.com/xai-org/grok-1/assets/93239683/adb4f9c3-0c4f-4272-8ced-1c49306bf1fd">

**Comment by ad1tyac0des** [comment]
> @ad1tyac0des it creates temp folder with over 300GB in it, do you have that space on the hard drive?

I had about 100GB of storage left, but at the moment when the error occurred, my system's RAM was completely utilized. This seems to be the reason why the program stopped. It looks like the problem was due to the high RAM usage rather than storage space.

**Comment by bluevisor** [comment]
https://github.com/xai-org/grok-1/issues/38#issuecomment-2003933119

**Comment by malinichev** [comment]
- In the file `checkpoint.py `I'm changing `/dev/shm/` to './dev/shm/'
- in the terminal `mkdir -p ./dev/shm/`
- after that, I run `python run.py `

But my macbook m1 pro with 16/512gb, 
freezes after that! 
because python eats up all my memory)

**Comment by surak** [comment]
> am at 272/300 gb right now. excitement starts to kick in, lets hope this thing runs.
> only having 6x 4090 (144GB VRAM) and 512GB RAM, if this isnt enough to at least run it, regardless of the speed, then something is off

It is probably not. I have 4 A100 and 512gb per node as well and I am not sure I can run it. It's stuck at loading checkpoints for a while now.

**Comment by Christmas-Wong** [comment]
you should install jaxlib for cuda, so that your 8 GPUs can be detected. or you can set local_mesh_config=(1, 1), and grok will run on cpu.

**Comment by SamKnightV** [comment]
> * In the file `checkpoint.py `I'm changing `/dev/shm/` to './dev/shm/'
> * in the terminal `mkdir -p ./dev/shm/`
> * after that, I run `python run.py `
> 
> But my macbook m1 pro with 16/512gb, freezes after that! because python eats up all my memory) I assume that there is not enough memory for the ssd

After did it i got an error zsh: killed     python run.py

**Comment by surak** [comment]
> > * In the file `checkpoint.py `I'm changing `/dev/shm/` to './dev/shm/'
> > * in the terminal `mkdir -p ./dev/shm/`
> > * after that, I run `python run.py `

> > But my macbook m1 pro with 16/512gb, freezes after that! because python eats up all my memory) I assume that there is not enough memory for the ssd
> After did it i got an error zsh: killed python run.py

We are talking about machines with 512gb of RAM and hundreds of gb of VRAM not being able to run it, not in a laptop. You will have to wait for a WAY smaller version of it to run in a small machine.

**Comment by SamKnightV** [comment]
I have Imac with processor 3,6 GHz 10-Core Intel Core i9 Graphics AMD Radeon Pro 5300 4 GB and memory 16 GB 2667 MHz DDR4 ))) What i need to change?

**Comment by surak** [comment]
))))

You need a real data center gpu compute node with at least 8 x A100 with 80gb to run grok at this point. I doubt that any quantized version would fit on a Mac anytime soon, but who knows? )))

**Comment by Na-Yun1990** [comment]
raise ValueError(f'Number of devices {len(devices)} must equal the product '
ValueError: Number of devices 1 must equal the product of mesh_shape (1, 8)
好吧~.~老马是真的一点不留情面啊。普通人还是老老实实的玩玩grok或者gpt什么的吧。这玩意你设备不达标，他是死活不会让你用的。等老子发达了，再搞他24块4090组个服务器爽爽！

**Comment by Na-Yun1990** [comment]
> I have Imac with processor 3,6 GHz 10-Core Intel Core i9 Graphics AMD Radeon Pro 5300 4 GB and memory 16 GB 2667 MHz DDR4 ))) What i need to change?

You need to change all.Ordinary civilian equipment cannot run this.Maybe Amazon cloud server can run grok-1. But the price will definitely be high

**Comment by Tirbo06** [comment]
> > looks like i have to set
> > ```
> >         widening_factor=6,
> >         num_kv_heads=6,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the TransformerConfig to the number of devices as well
> 
> 


Do you have a good amount of RAM ?
