### ISSUE TITLE
I have errors that the file does not exist and the process is occupied asynchronously

### ISSUE THREAD

**Issue by xhzwjc** [xai-org/grok-1#88]
INFO:rank:Loading checkpoint at ./checkpoints/ckpt-0
Traceback (most recent call last):
  File "C:\Users\w2983\Desktop\grok-1\checkpoint.py", line 52, in copy_to_shm
    shutil.copyfile(file, tmp_path)
  File "C:\Users\w2983\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/ckpt-0\\tensor00000_000'

File "C:\Users\w2983\Desktop\grok-1\checkpoint.py", line 55, in copy_to_shm
    os.remove(tmp_path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: '\dev\shm\\tmpri0li3ul'

**Comment by xhzwjc** [comment]
I have tried some methods, but still can't solve this problem, my brain is dying recently

**Comment by xhzwjc** [comment]
@ibab @jaimealonso @madaan @chentingpc

**Comment by yarodevuci** [comment]
@xhzwjc surround it with try except block ... 
issue is where file is not closed and python code wants to delete that temp file.

**Comment by xhzwjc** [comment]
@yarodevuci 
I have adopted
